### ISSUE TITLE
Integration fails to initialise if a USB Bluetooth adaptor is present.

### ISSUE THREAD

**Issue by agittins** [agittins/bermuda#19]
Logs show:

```
This error originated from a custom integration.

Logger: custom_components.bermuda
Source: custom_components/bermuda/__init__.py:314
Integration: Bermuda BLE Triangulation (documentation, issues)
First occurred: 25 August 2023 at 19:58:13 (1967 occurrences)
Last logged: 01:26:08

Unexpected error fetching bermuda data: 'XX:XX:XX:XX:XX:XX'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bermuda/__init__.py", line 314, in _async_update_data
    self.devices[discovered.scanner.source].area_id,
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'XX:XX:XX:XX:XX:XX'
```

Where `XX:XX:XX:XX:XX:XX` is the MAC address of the USB bluetooth adaptor installed in the system.

## Version of the custom_component

All versions up to v0.2.1 inclusive.

## Describe the bug

Faulty logic in `_refresh_scanners` fails to find bluetooth usb adaptors.

**Comment by agittins** [comment]
Fixed in release v0.2.2 by commit #23
