### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by Drewskieza** [agittins/bermuda#225]
## Version of the custom_component

Bermuda 0.6.7
HA 2024.06.04

## Configuration

![image](https://github.com/agittins/bermuda/assets/34630805/f1491a81-81f1-43cf-b016-7f49732ce5fb)
![image](https://github.com/agittins/bermuda/assets/34630805/7f9eaa07-4317-4ccc-840c-74b42a229541)

## Describe the bug

Bermuda is failing to start

## Debug log

```text

2024-06-28 10:22:32.733 ERROR (MainThread) [custom_components.bermuda] Unexpected error fetching bermuda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bermuda/coordinator.py", line 446, in _async_update_data
    device.beacon_type.add(BEACON_IBEACON_SOURCE)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'add'
2024-06-28 10:22:42.488 INFO (MainThread) [homeassistant.components.mqtt.discovery] Found new component: binary_sensor cc01e1da-0848-485f-a4cd-a1119c539078 812beee8-fd95-489c-89a3-6ec214119e19_motion
2024-06-28 10:22:55.567 INFO (MainThread) [hass_nabucasa.google_report_state] Timeout while waiting to receive message
2024-06-28 10:22:58.152 ERROR (MainThread) [custom_components.bermuda] Unexpected error fetching bermuda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bermuda/coordinator.py", line 446, in _async_update_data
    device.beacon_type.add(BEACON_IBEACON_SOURCE)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'add'

2024-06-28 10:29:35.061 ERROR (MainThread) [custom_components.bermuda] Unexpected error fetching bermuda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bermuda/coordinator.py", line 446, in _async_update_data
    device.beacon_type.add(BEACON_IBEACON_SOURCE)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'add'
2024-06-28 10:29:35.062 DEBUG (MainThread) [custom_components.bermuda] Finished fetching bermuda data in 0.005 seconds (success: False)
2024-06-28 10:29:35.062 DEBUG (MainThread) [custom_components.bermuda] Coordinator last update failed, rasing ConfigEntryNotReady

```

**Comment by agittins** [comment]
Howdy!

That seems really odd - the error about `beacon_type` having no `add` method is because it's appearing as a "list", but `beacon_type` *should* be defined as a `set` not a `list`, in `bermuda_device.py:56`

Is it possible that your system is somehow picking up some other version of the bermuda files from somewhere, or that the source files were modified somehow? Did you install using HACS or manually? That error "shouldn't" be possible from the files in v0.6.7, but I might be missing something there.

**Comment by Drewskieza** [comment]
Hi,
Addded custome repository via the link on this site.
Then installed from HACS.
Let me try uninstall and start again.

**Comment by Drewskieza** [comment]
Hi,
Uninstalled did a full host reboot.
Reinstalled restarted
Now it works :)

**Comment by agittins** [comment]
Great! Thanks for the update.
