### ISSUE TITLE
Creation of distance sensor fails to add state_class & unit_of_measurement

### ISSUE THREAD

**Issue by jaymunro** [agittins/bermuda#57]
## Version of the custom_component

0.3.1 (note this is 0.0.0 in the const.py file and should be set correctly?)

## Describe the bug

The sensors created for distance are missing `state_class` and `unit_of_measurement` properties and so they are shown as text rather than graphed.

<img width="419" alt="Screenshot 2023-10-30 at 6 12 23 PM" src="https://github.com/agittins/bermuda/assets/1166024/99d272ed-45e2-492d-a9c5-02b0db8a0fe7">

<img width="949" alt="Screenshot 2023-10-31 at 8 53 59 AM" src="https://github.com/agittins/bermuda/assets/1166024/196ab62a-4683-499c-a0a8-70a20c3adbf3">

These properties seem to be missing in the distance sensors:
```
      state_class: measurement
      unit_of_measurement: m
```

## Debug log

```text

2023-10-30 19:02:14.641 DEBUG (MainThread) [custom_components.bermuda] Finished fetching bermuda data in 0.035 seconds (success: True)
2023-10-30 19:02:19.632 DEBUG (MainThread) [custom_components.bermuda] Finished fetching bermuda data in 0.026 seconds (success: True)
2023-10-30 19:02:24.631 DEBUG (MainThread) [custom_components.bermuda] Finished fetching bermuda data in 0.025 seconds (success: True)
2023-10-30 19:02:29.633 DEBUG (MainThread) [custom_components.bermuda] Finished fetching bermuda data in 0.027 seconds (success: True)
2023-10-30 19:02:34.631 DEBUG (MainThread) [custom_components.bermuda] Finished fetching bermuda data in 0.026 seconds (success: True)
2023-10-30 19:02:39.639 DEBUG (MainThread) [custom_components.bermuda] Finished fetching bermuda data in 0.033 seconds (success: True)
2023-10-30 19:02:44.631 DEBUG (MainThread) [custom_components.bermuda] Finished fetching bermuda data in 0.025 seconds (success: True)
2023-10-30 19:02:48.594 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Bermuda BLE Trilateration for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 565, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 132, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-10-30 19:02:48.685 DEBUG (MainThread) [custom_components.bermuda] Device None now in Garage
2023-10-30 19:02:48.686 DEBUG (MainThread) [custom_components.bermuda] Device bhyve_2619B3 now in Bedroom - Master
2023-10-30 19:02:48.687 DEBUG (MainThread) [custom_components.bermuda] Finished fetching bermuda data in 0.038 seconds (success: True)
2023-10-30 19:02:48.767 DEBUG (MainThread) [custom_components.bermuda] Device None now in Garage
2023-10-30 19:02:48.768 DEBUG (MainThread) [custom_components.bermuda] Device bhyve_2619B3 now in Bedroom - Master
2023-10-30 19:02:48.768 DEBUG (MainThread) [custom_components.bermuda] Finished fetching bermuda data in 0.032 seconds (success: True)
2023-10-30 19:02:48.779 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Bermuda BLE Trilateration for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 126, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-10-30 19:02:48.844 DEBUG (MainThread) [custom_components.bermuda] Finished fetching bermuda data in 0.034 seconds (success: True)
2023-10-30 19:02:53.347 ERROR (MainThread) [frontend.js.latest.202310050] Uncaught error from Chrome 118.0.0.0 on Mac OS 10.15.7
TypeError: Cannot read properties of undefined (reading 'id')
_keyFunction (src/components/data-table/ha-data-table.ts:362:56)
keyFunction (src/virtualize.ts:116:41)
r (src/directives/repeat.ts:56:28)
ct (src/directives/repeat.ts:93:52)
update (src/directive.ts:134:16)
_$AS (src/lit-html.ts:1085:23)
S (src/lit-html.ts:1362:12)
_$AI (src/async-directive.ts:366:18)
setValue (src/virtualize.ts:139:13)
dispatchEvent (src/Virtualizer.ts:802:23)
2023-10-30 19:02:53.550 DEBUG (MainThread) [custom_components.bermuda] Finished fetching bermuda data in 0.030 seconds (success: True)
2023-10-30 19:02:58.547 DEBUG (MainThread) [custom_components.bermuda] Finished fetching bermuda data in 0.026 seconds (success: True)
2023-10-30 19:03:03.543 DEBUG (MainThread) [custom_components.bermuda] Device None now in Garage
2023-10-30 19:03:03.544 DEBUG (MainThread) [custom_components.bermuda] Finished fetching bermuda data in 0.025 seconds (success: True)
2023-10-30 19:03:08.546 DEBUG (MainThread) [custom_components.bermuda] Finished fetching bermuda data in 0.026 seconds (success: True)
```

**Comment by jaymunro** [comment]
For a device (Eve Motion) created with the original names set be the integration:

**core.device_registry**
```
{
  "area_id": null,
  "config_entries": [
    "94e5a656f49dfc58f3355df6a187aa6f"
  ],
  "configuration_url": null,
  "connections": [],
  "disabled_by": null,
  "entry_type": null,
  "hw_version": null,
  "id": "73baf50fe95a07129d87807860eaea5c",
  "identifiers": [
    [
      "bermuda",
      "fb:16:a8:31:f0:af"
    ]
  ],
  "manufacturer": "Bermuda BLE Trilateration",
  "model": "0.0.0",
  "name_by_user": null,
  "name": "Eve",
  "sw_version": null,
  "via_device_id": null
}
```
**core.entity_registry**
```
      {
        "aliases": [],
        "area_id": null,
        "capabilities": null,
        "config_entry_id": "94e5a656f49dfc58f3355df6a187aa6f",
        "device_class": null,
        "device_id": "73baf50fe95a07129d87807860eaea5c",
        "disabled_by": null,
        "entity_category": null,
        "entity_id": "sensor.eve_motion_d91b_distance",
        "hidden_by": null,
        "icon": null,
        "id": "e4dd6d6d196ced731ae26a21fb2495b9",
        "has_entity_name": true,
        "name": null,
        "options": {
          "conversation": {
            "should_expose": false
          }
        },
        "original_device_class": "distance",
        "original_icon": null,
        "original_name": "Distance",
        "platform": "bermuda",
        "supported_features": 0,
        "translation_key": null,
        "unique_id": "fb:16:a8:31:f0:af_range",
        "unit_of_measurement": null
      },
      {
        "aliases": [],
        "area_id": null,
        "capabilities": null,
        "config_entry_id": "94e5a656f49dfc58f3355df6a187aa6f",
        "device_class": null,
        "device_id": "73baf50fe95a07129d87807860eaea5c",
        "disabled_by": null,
        "entity_category": null,
        "entity_id": "sensor.eve_motion_d91b_area",
        "hidden_by": null,
        "icon": null,
        "id": "50246bcb49772213ca985943e38bc0c2",
        "has_entity_name": true,
        "name": null,
        "options": {
          "conversation": {
            "should_expose": false
          }
        },
        "original_device_class": "bermuda__custom_device_class",
        "original_icon": null,
        "original_name": "Area",
        "platform": "bermuda",
        "supported_features": 0,
        "translation_key": null,
        "unique_id": "fb:16:a8:31:f0:af",
        "unit_of_measurement": null
      }
```

The `device_tracker.bermuda_fb_16_a8_31_f0_af` entity is not present in the registry however it does get listed in `Developer tools > STATES`

<img width="795" alt="Screenshot 2023-10-30 at 7 31 25 PM" src="https://github.com/agittins/bermuda/assets/1166024/943c5f35-c3e5-42cf-9894-4672a8407f7c">

**Comment by jaymunro** [comment]
I see the device_tracker matter is on the to_do list so will edit the comments related to another issue for clarity of understanding.

**Comment by agittins** [comment]
Hi Jay! Sorry it has taken so long for me to respond to this, I have been pretty flat out lately.

Really appreciate the detail you took the time to capture (and your PR). The `state_class` and `unit_of_measurement` properties should have been in the 0.3.1 release already, as they were added in commit https://github.com/agittins/bermuda/commit/7a039743013248717d0dd13b3cf7db40545c4e7e#diff-2304201eb65a16c0cb617eb9d959701fab20873a3a430c0f0fbbcc665bb9e77f

(unless I'm reading the history wrong, which is entirely possible). It's likely that if you had installed a version prior to 0.3.1 then the historical entries would have been saved without their UOM and the UI won't show them to you in the graphed format - IIRC on my system I had to go into `Developer Tools`, `Statistics` and choose `FIX ISSUE` on the fields so HA will add the units to the historical records, and then the UI would show the graph.

Can you give that a try and let me know how it goes? I don't know if maybe it will have solved itself over time if your history is on the default 10-day rollover.

If I am wrong about the commit history, then the change might only be in the `main` branch and not in 0.3.1 - I plan to do a release very soon so that should roll that up, or you could try the `main` branch otherwise.

If it's still a problem on your install let me know and I'll dig further.

**Comment by jaymunro** [comment]
Just checked and the values are now displaying as a graph in metres.
I think 0.3.1 was the only version I had installed, so not sure why this happened. Hopefully it doesn't happen to others too.
Closing...
